import React from 'react';
import { Link } from "react-router-dom";
import { Map } from '@cryptosat/cryptosim-visualization';
import { Console } from '@cryptosat/jsconsole';
import CodeSnippet from '../CodeSnippet';
import './Lesson.css';
import payload from './basePayload';

import SimulatedClock from '@cryptosat/cryptosim/lib/clocks/simulatedClock';
import GeoCoordinates from '@cryptosat/cryptosim/lib/geoCoordinates';
import GroundStationNetwork from '@cryptosat/cryptosim/lib/groundStationNetwork';
import Universe from '@cryptosat/cryptosim/lib/universe';

const MainClient = require('@cryptosat/cryptosim/lib/clients/main');
const MainService = require('@cryptosat/cryptosim/lib/services/main');
const Satellite = require('@cryptosat/cryptosim/lib/satellite');
const GroundStation = require('@cryptosat/cryptosim/lib/groundStation');


const content = (
  <div>
    <h2>Asynchrony</h2>
    <p>
     When the cryptosat is offline the Cryptosat service caches transmission for
     non-interactive requests. Non-interactive requests are requests that do
     not depend on inputs from the end user but rather only on values generated
     unilaterally by the cryptosat. For such requests the Cryptosat API returns
     the most recent value generated from the cryposat and received via one of
     the ground stations. Responses typically contain a timestamp to indicate
     the exact time the value was generated by the cryptosat. 
    </p>
    <p>
      Interactive requests are queued and sent to the cryptosat when it’s
      online. The Cryptosat API returns a tracker object which can be used to
      query the status of the request. For example, when issuing a signing
      request:
    </p>
    <CodeSnippet code={`tracker = cryptosat.sign('hello, world!');`} />
    <p>
      The tracker object can be queried in the following manner to determine the
      status of the request:
    </p>
    <CodeSnippet code={`tracker.status();`} />
    <p>
      The status can be one of <i>Pending</i>, <i>Sent</i> and <i>Ready</i>.
      A <i>Pending</i> status indicates the request is waiting for the cryptosat
      to come online to transmit the request. A <i>Sent</i> status indicates the
      request has been transmitted and acknowledged by the cryptosat.
      A <i>Ready</i> status indicates the request has been processed and the
      result is ready to be consumed by the user. To obtain the result of the
      operation issue the following call:
    </p>
    <CodeSnippet code={`tracker.result();`} />
    <p>
      The result will return null until the status of the request
      is <i>Ready</i>.
    </p>

  </div>
);

class LessonAsynchrony extends React.Component {

  constructor(props) {
    super(props);
    this.payload = payload;
    const clock = new SimulatedClock(new Date(2021, 2, 1, 6, 50, 0, 0));
    clock.play();
    const universe = new Universe(clock);
    const ISS_TLE = [
      '1 25544U 98067A   21027.77992426  .00003336  00000-0  68893-4 0  9991',
      '2 25544  51.6465 317.1909 0002399 302.6503 164.1536 15.48908950266831',
    ];
    const sat = new Satellite(universe, 'crypto1', ISS_TLE[0], ISS_TLE[1]);
    const gsnetwork = GroundStationNetwork.load(
        universe, require('@cryptosat/cryptosim/data/rbcNetwork'));
    const mainService = new MainService(universe);
    sat.bindService('main', mainService);
    this.payload.cryptosat = new MainClient(universe, sat, gsnetwork, 'main');
    this.payload.universe = universe;
    this.payload.gsnetwork = gsnetwork;
  } 

 render() {
    const zoom = 2.5;
    const center = new GeoCoordinates(40.567952, -98.518132, 0);
    return(
        <div className='split-pane-horizontal'>
          <div className='left-pane'>
            <div className='lesson'>
              <div className="lesson-content">
                {content}
              </div>
              <div className="pager">
                <Link to={this.props.previous}>&lt; Previous</Link>
                <Link to={this.props.next}>Next &gt;</Link>
              </div>
            </div>
          </div>
          <div className='right-pane'>
            <div className='top-pane'>
              <Console payload={payload} theme='dark'/>
            </div>
            <div className='bottom-pane'>
              <Map universe={this.payload.universe}
                   gsnetwork={this.payload.gsnetwork}
                   center={center} zoom={zoom} />
            </div>
          </div>
        </div>
    )
  }
}

export default LessonAsynchrony
